import common from "../../common/tools/strings";

const strings = {
    en: {
        targetCalculator: {
            "calculator_header" : "Calculator",
            "calculator_desc": "Find out when you will reach your goal.",
            "calculator_action": "Enter values to get an estimate",
            "calculator_result": "Result",
            "now_header": "Current value of investments",
            "now_placeholder": "Current Investments",
            "goal_header": "Investments Target Value",
            "goal_placeholder": "Enter target / leave empty",
            "goal_info":"1) If you leave the target empty, financial independence is used as you goal.",
            "income_per_month": "Net Income / Month",
            "costs_per_month":"Costs / Month",
            "fill": "Enter",
            "investments_interest_rate": "Annual Interest Rate (%)",
            "show_estimate": "Calculate",
            "reportGoal": "Target",
            // Result
            "result_now": "Investments in the beginning",
            "result_yearly": "Saved and invested from income tot. ",
            "result_estimated_growth": "Estimated investment growth tot. ",
            "result_total": "Total investments ",
            "result_goal_is":"Your target is ",
            "result_fire":"financial independence (",
            "result_pre_text":") and you will reach it on",
            "result_remaining":" Time remaining is",
            "result_join_now":"It seems that have some work to do to get to your goal. Get there faster by ",
            "result_join_link":"joining",
            "edit_info":"Edit",
            "after_year": "years and ",
            "after_month": "months.",
            "after_day": "days",
            "calc_info":"*Calculator expects that the difference between income and cost is invested at beginning of each month. ",
            "calc_info_details": "If you left the target field empty, it is calculated according to 4% rule. It's a rough estimate and anything can happen in real life. We reserve the rights to mistakes. More on ",
             // Details
             "d_assets_title":"Investments",
             "d_assets":"Enter your current investments value. If you also enter other assets, take that into account in 'Annual Interest Rate'.",
             "d_income_title":"Income",
             "d_income":"Enter your average monthly net income. Calculator expects that the difference between income and costs is invested.",
             "d_cost_title":"Costs",
             "d_cost":"Your average monthly costs. Calculator expects that the difference between income and costs is invested.",
             "d_goal_title":"Target",
             "d_goal":"How big investment portfolio do you want? You can also calculate other asset goals but take it into account in 'Annual Interest Rate'. If you want to you financial independence as your target, leave this field empty.",
             "d_interest_title":"Annual Interest Rate",
             "d_interest":"Annual interst rate depend of your investment portfolio. E.g. in stocks it has historically been between 5-8 %:n, in bonds between 2-5 % and in bank accounts close to zero. If you have multiple asset classes, use the average. If you start from negative capital, interest rate is applied only after you reach positive value.",
             "d_cancel":"Cancel",
             // errors
             "e_api_not_running": "Unfortunatelly the calculator is broken. You can send feedback to info@pohatta.com.",
             "e_too_many_req": "Wow! You've been busy! Just wait a few minutes and then try again. You can send feedback to info@pohatta.com.",
             "e_too_long":"Ouch... it would take over 30 years to reach your target so the calculator run out of memory. Could you make more money or spend less?",
             "e_negative_goal":"It would seem that with current inputs your investments will not grow.",
             "e_goal_less_than_current":"Congratulations! You have already reached your target. Your investments value is greater than your target.",
             // invite
             "welcome_to_invite_list":"Welcome!",
             "e_email_exists":"You have already joined.",
             ...common.en.common,
        },
    },
    fi: {
        targetCalculator: {
            "calculator_header": "Tavoitelaskuri",
            "calculator_desc": "Selvitä milloin saavutat sijoitustavoitteesi.",
            "calculator_action": "Syötä tiedot saadaksesi arvio",
            "calculator_result": "Tulos",
            "now_header": "Sijoitusvarallisuutesi nyt",
            "now_placeholder": "Syötä sijoitusvarallisuutesi",
            "goal_header": "Sijoitusvarallisuustavoitteesi",
            "goal_placeholder": "Syötä tavoitteesi / jätä tyhjäksi",
            "goal_info":"1) Jos jätät kentän tyhjäksi, käytetään tavoitteena taloudellisen riippumattomuuden saavuttamista.",
            "income_per_month": "Tulosi (netto) /kk",
            "costs_per_month":"Menosi / kk",
            "fill": "Syötä",
            "investments_interest_rate": "Sijoituksien vuosituotto (%)",
            "show_estimate": "Näytä arvio",
            // Result
            "result_now": "Sijoitusvarallisuus alussa",
            "result_yearly": "Tuloista säästetty ja sijoitettu yht. ",
            "result_estimated_growth": "Sijoitusten arvioitu tuotto yht. ",
            "result_total": "Arviotu varallisuus yht. ",
            "result_goal_is":"Tavoitteesi on ",
            "result_fire":"taloudellinen riippumattomuus eli ",
            "result_pre_text":"ja saavutat sen noin",
            "result_remaining":" Aikaa jäljellä",
            "result_join_now":"Näyttäisi, että tavoitteeseesi on vielä matkaa. Lisää vauhtia ja ",
            "result_join_link":"liity mukaan",
            "edit_info":"Muokkaa tietoja",
            "after_year": "vuotta ja ",
            "after_month": "kuukautta.",
            "after_day": "päivän kuluttua",
            "calc_info":"*Laskuri olettaa, että tulojen ja menojen välinen erotus sijoitetaan jokaisen kuukauden alussa. ",
            "calc_info_details": "Jos jätit tavoitteen tyhjäksi, lasketaan tavoite 4% säännön mukaan. Tämä on karkea arvio ja todellisuudessa voi tapahtua mitä vain. Pidätämme oikeudet virheisiin. Lisätietoja ",
            // Details
            "d_assets_title":"Sijoitusvarallisuus",
            "d_assets":"Syötä kenttään nykyinen sijoitusvarallisuutesi. Jos syötät myös muuta varallisuutta kuten asunnon, muista huomioida tämä kohdassa 'vuosituotto'.",
            "d_income_title":"Tulot",
            "d_income":"Syötä nettotulosi. Jos kuukausittaisissa tuloissasi on suurta vaihtelua, käytä esimerkiksi vuoden keskiarvoa. Laskuri olettaa, että tulojen ja menojen välinen erotus sijoitetaan.",
            "d_cost_title":"Menot",
            "d_cost":"Syötä menosi yhteenlaskettuna. Jos kuukausittaisissa menoissasi on suurta vaihtelua, käytä esimerkiksi vuoden keskiarvoa. Laskuri olettaa, että tulojen ja menojen välinen erotus sijoitetaan.",
            "d_goal_title":"Tavoite",
            "d_goal":"Kuinka paljon sijoitusvarallisuutta haluat kerätä? Voit laskea myös muun varallisuuden tai säästämisen tavoitteen, mutta huomioi se kohdassa 'vuosituotto'. Jos haluat käyttää tavoitteena taloudellista riippumattomuutta, jätä kenttä tyhjäksi.",
            "d_interest_title":"Vuosituotto",
            "d_interest":"Vuosituotto riippuu sijoituksistasi. Esimerkiksi osakkeiden pitkän aikavälin vuosituotto on vaihdellut 5-8 %:n välillä. Joukkovelkakirjoissa luku on 2-5 %:a ja pankkitileillä lähes nolla. Jos sinulla on monia sijoituskohteita, käytä keskiarvoa. Jos aloitat negatiivisesta sijoitusvarallisuudesta, korko on voimassa vasta pääoman ollessa positiivinen.",
            // errors
            "e_api_not_running": "Laskuri on valitettavasti rikki. Laita palautetta tulemaan: info@pohatta.com.",
            "e_too_many_req": "Kylläpä sinulla riittää intoa! Valitettavasti, nyt joudut hetken odottamaan. Palautetta voit laittaa: info@pohatta.com",
            "e_too_long":"Oi voi... kestäisi yli 30 vuotta saavuttaa tavoite, joten laskurista loppuivat rivit kesken. Olisiko mahdollista kasvattaa tulojasi? Entä säästää kuluissasi?",
            "e_negative_goal":"Näyttäisi, että nykyisillä arvoilla sijoituksesi ei kasva.",
            "e_goal_less_than_current":"Onneksi olkoon, olet jo tavoitteessasi! Varallisuutesi on suurempi kuin tavoitteesi ",
            // invite
            "welcome_to_invite_list":"Mahtavaa, että innostuit ja tervetuloa mukaan!",
            "e_email_exists":"Sähköposti on jo kutsulistalla.",
            ...common.fi.common,

            //todo
            "d_cancel":"Cancel"
        }
    },
};

export default strings