const strings = {
    en: {
        landing: {
            "main_title" : "Smarter Personal Finance",
            "main_description" : "Make your financial dream a reality. Check the calculator to see when you will reach your dream",
            "main_button":"Calculator",
            "coming_soon": "Coming soon",
            "target_header": "Set a Target",
            "target_description": "Start the journey to your dream by creating a target. Usually setting a target helps you to get there, but it's also possible to use the service without one.",
            "track_header": "Easier Recording",
            "track_description": "By recording transactions and balances you can actually see where you are. This service will make it easier for you to collect data and manage your finances. In the future we can collect the data for you if you wish.",
            "plan_header": "Smarter Planning",
            "plan_description": "With planning you will be able to see what is actually required to target your target. Planning is an advanced version of the calculator and in the future you can simulate for example how does a daily cup of coffee affect you finances.",
            // pricing
            "pricing_title": "Pricing",
            "pricing_description": "Basic makes things easier, VIP does the work for you.",
            "free": "Basic",
            "free_description": "You get to use all the features but without automatically data retrieval.",
            "free_per_month": "0.5",
            "free_description_bottom": "*Billed annually",
            "paid": "VIP",
            "paid_description": "Bank account transactions will be collected automatically and you can just enjoy the results.*",
            "paid_description_bottom": "*Coming later",
            "price_per_month": "6",
            "join_invitelist": "Join invite list",
            // security
            "security_title": "Security",
            "security_description": "We will look after you data and won't give any of it to third parties. If you choose so, you can delete all your data with a single click.",
            // join
            "join_title": "The Service is Under Development ",
            "join_description_1": `Pre-orders are closed. `,
            "join_description_2": `Kutsulistalle mahtuu 50 nopeinta, joista jokainen saa pysyvän 50 % alennuksen. Lisäksi teen parhaani, että lisätiedoissa kertomasi tärkein asia on valmis avajaisissa. `,
            "join_description_7": `*Your email is only used for the invitation and will be removed after the invitation is sent.`,
            "join_description_pohatta": `- P.Ohatta`,
            "join_description_email": `info@pohatta.com`,
            "join_blog_1":"Lisää tietoa ",
            "join_blog_2":"blogissa",
            "join_description_6": `. Toivottavasti innostut ja lähdet mukaan!`,
            "join_late":"All pre-order seats reserved. If you missed your spot, send email to " ,
            "join_late_2":" and you will be among the first to know when the service is fully open.",
        },
    },
    fi: {
        landing: {
            "main_title": "Hallitse talouttasi fiksummin",
            "main_description": "Tee taloudellisesta tavoitteestasi totta – olkoon se kolmevitosena eläkkeelle tai jotain ihan muuta. Kokeile laskurin avulla milloin saavutat tavoitteesi. Verkkopalvelu aukeaa myöhemmin.",
            "main_button": "Kokeile laskuria",
            "coming_soon": "Tulossa pian",
            "target_header": "Aseta tavoitteesi",
            "target_description": "Aloita matkasi kohti unelmaasi luomalla itsellesi taloudellinen tavoite. Tavoitteen määrittely auttaa yleensä sinua löytämään perille, mutta palvelua voi käyttää myös ilman tavoitetta.",
            "track_header": "Seuraa vaivattomasti",
            "track_description": "Seurannan avulla tiedät missä olet menossa. Palvelu tekee tietojen keräämisestä vaivattomampaa ja helpottaa taloutesi seuraamista. Tulevaisuudessa keräämme tilitapahtumat automaattisesti puolestasi, jos niin toivot.",
            "plan_header": "Suunnittele fiksummin",
            "plan_description": "Suunnittelemalla näet mitä tavoitteen saavuttaminen konkreettisesti vaatii. Suunnittelu on edistyneempi versio tavoitelaskurista ja tulevaisuudessa voit kokeilla esimerkiksi kahvikupin vaikutusta talouteesi pidemmällä aikavälillä.",
            // pricing
            "pricing_title": "Hinnoittelu",
            "pricing_description": "Basic auttaa taloutesi hallinnassa, VIP tekee työt puolestasi.",
            "free": "Basic",
            "free_description": "Saat käyttöösi kaikki sovelluksen toiminnallisuudet ilman automatisointia.",
            "free_per_month": "0.5",
            "free_description_bottom": "*Laskutetaan vuosittain",
            "paid": "VIP",
            "paid_description": "Tilitapahtumat kerätään automaattisesti ja sinä voit vain ihailla lopputulosta.*",
            "paid_description_bottom": "*Tulossa myöhemmin",
            "price_per_month": "6",
            "join_invitelist": "Liity kutsulistalle",
            // security
            "security_title": "Tietoturva",
            "security_description": "Pidämme hyvää huolta tiedoistasi emmekä luovuta tietojasi kenellekään. Jos lopetat palvelun käytön, voit halutessasi poistaa kaikki tietosi yhdellä napin painalluksella.",
            // join
            "join_title": "Palvelua kehitetään parhaillaan",
            "join_description_1": `Ennakkotilaaminen on päättynyt. `,
            "join_description_2": `Kutsulistalle mahtuu 50 nopeinta, joista jokainen saa pysyvän 50 % alennuksen. Lisäksi teen parhaani, että lisätiedoissa kertomasi tärkein asia on valmis avajaisissa. `,
            "join_description_7": `*Sähköpostiasi käytetään vain kutsun lähettämiseen ja poistamme osoitteesi, kun olet saanut kutsun.`,
            "join_description_pohatta": `- P.Ohatta`,
            "join_description_email": `info@pohatta.com`,
            "join_blog_1":"Lisää tietoa ",
            "join_blog_2":"blogissa",
            "join_description_6": `. Toivottavasti innostut ja lähdet mukaan!`,
            "join_late":"Kaikki ennakkopaikat ovat täynnä. Jos missasit tilaisuutesi, niin laita sähköpostia " ,
            "join_late_2":" ja saat ensimmäisten joukossa tiedon, kun palvelu avataan.",
        }
    },
};

export default strings